services:
  lagrange-app:
    build: .
    image: 'germanandress/ovaarq-app:latest'
    ports:
      - '8080:8080'
    networks:
      - red-backend-app

networks:
  red-backend-app:
    driver: bridge